version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:156962844638:task-definition/kbAuth:1"
        LoadBalancerInfo:
          ContainerName: "auth"
          ContainerPort: "9095"
        PlatformVersion: "LATEST"
