
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - echo Manda@91688 | docker login --username kapilbodhare --password-stdin
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
    - IMAGE_URI=public.ecr.aws/p2e3u7x0/kb-repo:${TAG}
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - mvn clean package -Ddockerfile.skip
    - docker build --tag $IMAGE_URI .
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/p2e3u7x0
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' auth $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
